// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmGHXiHr9_wnNpCnr_Nv0xxouBNf6-7HM',
    appId: '1:337269433137:web:fdd54bf9342caef4f90610',
    messagingSenderId: '337269433137',
    projectId: 'test-project-649a7',
    authDomain: 'test-project-649a7.firebaseapp.com',
    storageBucket: 'test-project-649a7.firebasestorage.app',
    measurementId: 'G-118L4X7158',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC13zXUHMsH4Oh5NO6tsUDqNNSUxOV9RL0',
    appId: '1:337269433137:android:c24cb853b39f7642f90610',
    messagingSenderId: '337269433137',
    projectId: 'test-project-649a7',
    storageBucket: 'test-project-649a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2cwQQcufEmkZDsrkfX2zakwUPD92Nnf4',
    appId: '1:337269433137:ios:7122c005921258e4f90610',
    messagingSenderId: '337269433137',
    projectId: 'test-project-649a7',
    storageBucket: 'test-project-649a7.firebasestorage.app',
    iosBundleId: 'com.example.firebasewithnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2cwQQcufEmkZDsrkfX2zakwUPD92Nnf4',
    appId: '1:337269433137:ios:7122c005921258e4f90610',
    messagingSenderId: '337269433137',
    projectId: 'test-project-649a7',
    storageBucket: 'test-project-649a7.firebasestorage.app',
    iosBundleId: 'com.example.firebasewithnotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmGHXiHr9_wnNpCnr_Nv0xxouBNf6-7HM',
    appId: '1:337269433137:web:faa33570cca9fa84f90610',
    messagingSenderId: '337269433137',
    projectId: 'test-project-649a7',
    authDomain: 'test-project-649a7.firebaseapp.com',
    storageBucket: 'test-project-649a7.firebasestorage.app',
    measurementId: 'G-WRFMPTCJ0P',
  );
}
