name: firebasewithnotification
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  geolocator: ^13.0.2
  flutter_localization: ^0.3.2
  firebase_auth: ^5.5.1
  animations: ^2.0.11
  lottie: ^3.1.2
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.2.1
  provider: ^6.1.4
  flutter_svg: ^2.0.9
  carousel_slider: ^5.0.0
  material_color_utilities: ^0.11.1
  shared_preferences: ^2.2.2
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^7.0.1
  country_code_picker: ^3.3.0




  lucide_icons: ^0.257.0
  flutter_screenutil: ^5.9.0
  google_maps_flutter: ^2.5.0
  http: ^1.3.0
  sqflite: ^2.4.2
  path: ^1.9.1


dev_dependencies:
  flutter_native_splash: ^2.4.4

flutter_test:
  sdk: flutter

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/Pattern.png
    - images/Order food.png
    - images/Take Away.png
    - images/maps.png
    - assets/lang/
    - images/Sent Message.png
    - images/animation.png
    - images/balloon1.png
    - images/balloon2.png
    - images/plant.png
    - assets/success_animation.json
    - images/cheese-burger-details.png
    - images/Chicken_Burger.png
    - images/Onion Pizza.png
    - images/Spicy Shawarma.png
    - images/Empty State.png
    - images/Order ID.png
    - images/photo.png

    - images/Pattern (1).png
    - images/Notif.png
    - images/loc.png
    - images/Container.png
    - images/pizza(1).png
    - images/burger.png
    - images/sandwich.png
    - images/Rectangle 128.png
    - images/pizza.png
    - images/Frame 71.png
    - images/cheese_burger.png
    - images/chicken.png
#    - images/chicken_burger.png
    - images/Rectangle 128 (1).png
    - images/Rectangle 133.png
    - images/Rectangle 136.png
    - images/Group 3154.png
    - images/shopping_15402438 1.png
    - images/Group.png
    - images/Visa.png
    - images/Mastercard.png
    - images/Mask group.png
    - images/pizzaa.png
    - images/Ellipse 35.png
    - images/margarita-pizza.png
    - images/Mexican_Green_Wave.png
    - images/Peppy_Paneer.png
    - images/Pizza_Cheese.png
    - images/Vector (1).png
    - images/Courier.png
    - images/A.png
    - images/google.png
    - images/2021_Facebook_icon 1.png
    - images/sahlah.png
    - images/freepik--Device--inject-65.png
    - images/Celebration-cuate-1.png
    - images/Chicken_Burger.png
    - images/Menu_Photo.png

    - assets/dark_map_style.json


